#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d I II III IV V VI VII 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^3' follow=on
bspc rule -a Evince desktop='^2' follow=off
bspc rule -a mpv desktop='^7' follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Fondo de escritorio
feh --bg-fill --randomize ~/.config/bspwm/images/* &

#inicio de la barra polybar
~/.config/polybar/launch.sh &

#conky
pkill conky
~/.config/conky/conkyx-start.sh &

#Transparencias
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &

#miniaplicación para el wifi
pkill nm-applet
nm-applet


#Notificaciones dunst
#pkill dunst &
#dunst &

